FROM docker.elastic.co/kibana/kibana:8.13.0

# Install the Wazuh Kibana plugin (must match your Wazuh & Kibana versions)
RUN kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.7.0_8.13.0.zip
